---
- hosts: ubuntu
  become: true
  tasks:
    - name: install apache
      apt:
        name: apasdfsdfsdfds
        state: present
      ignore_errors: yes

    - shell: "touch {{ ansi_var }}"
   
    - shell: command="ls -all /home/devops/ansible/*.yml"
      register: reg_out

    - debug: msg="{{reg_out.stdout_lines}}"

    - name: update the template
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
        backup: yes
      notify: start service

    
  handlers:
     - name: start service
       service:
           name: apache2
           state: restarted


