---
- hosts: all
  become: yes
  tasks:
    - name: install git in deb
      apt:
        name:
          - git
          - wget
          - tree
        state: present
      when: ansible_os_family == "Debian"
   
    - name: install git in RHEL
      yum:
        name: 
          - git
          - wget
          - tree  
        state: present
      when: ansible_os_family == "RedHat"
