---
- hosts: all
  become: true
  # vars:
          #- java_ubuntu: openjdk-8-jdk
            #          - java_rhel: java-1.8.0-openjdk
  tasks:
          - name: install java in ubuntu
            apt:
                    name: "{{ java }}"
                    state: present
            when: ansible_os_family == "Debian"

          - name: install java in RHEL
            yum: 
                    name: "{{ java }}"
                    state: present
            when: ansible_os_family == "RedHat"
